# This is a workflow for HANGMAN

name: MY-Hangman

# Controls when the workflow will run
on:
  push:
    branches:
      - master

jobs:
  run-game:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
    
      - name: list dir
        run: ls -la
        
      - name: check version
        run: python3 --version

